version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSkiii
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork
  backend:
    image: ahmedayedi/gestion-station-ski:1.0
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationSkiii?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./m2:/root/.m2
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db: